### ISSUE TITLE
Twitter Error: unable to parse Integer '123141'

### ISSUE THREAD

**Issue by antonioalegria** [fbrunel/twitterdroid#1]
When I Change Account the app gives me the error "Twitter Error: unable to parse Integer '123141'" where '123141' is some bogus number.

**Comment by fbrunel** [comment]
The project has not been updated to reflect the changes in the Twitter API, esp. regarding big IDs. Also, the project won't work with OAuth for now.

**Comment by antonioalegria** [comment]
Ok, thx. Maybe If I have some spare time I'll contribute some OAuth support.

**Comment by fbrunel** [comment]
Thanks.
